{% set name = "westpa" %}
{% set version = "2020.03" %}
{% set sha256 = "0a1f7b30f405a0f3ca1d9808adbf10fb93451cfd2b79c4ce992ff5cedcb65c3d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/westpa/westpa/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools
    - python
    - cython
    - numpy 1.16.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - h5py 2.10.*
    - pyyaml 5.3.*
    - pyzmq 19.0.*
    - matplotlib-base
    - blessings 1.7.*
    - ipykernel

test:
  commands:
    - "source ${PREFIX}/${PKG_NAME}-${PKG_VERSION}/westpa.sh"
    - "source ${WEST_ROOT}/bin/w_env"
    - "$WEST_PYTHON -c 'import west'"
    - "$WEST_PYTHON -c 'import west.propagators'"
    - "$WEST_PYTHON -c 'import westpa'"
    - "$WEST_PYTHON -c 'import westpa.binning'"
    - "$WEST_PYTHON -c 'import westpa.kinetics'"
    - "$WEST_PYTHON -c 'import westpa.reweight'"
    - "$WEST_PYTHON -c 'import work_managers'"
    - "$WEST_PYTHON -c 'import westtools'"
    - "$WEST_PYTHON -c 'import fasthist'"
    - "$WEST_PYTHON -c 'import mclib'"
    # Currently blocked by https://github.com/westpa/westpa/issues/70
    #- "$WEST_PYTHON -c 'import trajtree'"

about:
  home: https://westpa.github.io/westpa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Interoperable, highly-scalable software for weighted ensemble simulation.'

  description: |
    WESTPA is a package for constructing and running stochastic simulations
    using the "weighted ensemble" approach of Huber and Kim (1996).
  doc_url: https://westpa.github.io/westpa/sphinx_index.html#tutorials
  dev_url: https://github.com/westpa

extra:
  recipe-maintainers:
    - mczwier
    - ajoshpratt
    - synapticarbors
    - burntyellow
    - ltchong
